language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.m2

before_install:
  - yes | sdkmanager "platforms;android-27"
