language: android

before_install:
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

install:
  - true

android:
  components:
    - build-tools-23.0.0
    - android-23

jdk:
  - oraclejdk7
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.m2