language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-24
    - extra
    - extra-android-m2repository

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.m2
